WebApplication1/WebApplication1/Areas/Cadastros/Controllers/FabricantesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Modelo.Cadastros;
using Servico.Cadastros;

namespace WebApplication1.Areas.Cadastros.Controllers
{
    public class FabricantesController : Controller
    {
        private FabricanteServico fabricanteServico = new FabricanteServico();
        private ActionResult ObterVisaoFabricantePorId(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(
                HttpStatusCode.BadRequest);
            }
            Fabricante fabricante = fabricanteServico.ObterFabricantePorId((long)id);
            if (fabricante == null)
            {
                return HttpNotFound();
            }
            return View(fabricante);
        }
        private ActionResult GravarFabricante(Fabricante fabricante)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    fabricanteServico.GravarFabricante(fabricante);
                    return RedirectToAction("Index");
                }
                return View(fabricante);
            }
            catch
            {
                return View(fabricante);
            }
        }
        // GET: Fabricantes
        public ActionResult Index()
        {
            return View(fabricanteServico.ObterFabricantesClassificadosPorNome());
        }
        // GET: Create
        public ActionResult Create()
        {
            return View();
        }
        // POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Fabricante fabricante)
        {
            return GravarFabricante(fabricante);
        }
        // GET: Edit
        public ActionResult Edit(long? id)
        {
            return ObterVisaoFabricantePorId(id);
        }
        // POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Fabricante fabricante)
        {
            return GravarFabricante(fabricante);
        }
        // GET: Details
        public ActionResult Details(long? id)
        {
            return ObterVisaoFabricantePorId(id);
        }
        // GET: Delete
        public ActionResult Delete(long? id)
        {
            return ObterVisaoFabricantePorId(id);
        }
        // POST: Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(long id)
        {
            try
            {
                Fabricante fabricante = fabricanteServico.EliminarFabricantePorId(id);
                TempData["Message"] = "Fabricante " + fabricante.Nome.ToUpper() + " foi removido";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/WebApplication1/Views/Fabricantes/Delete.cshtml
@model Modelo.Cadastros.Fabricante
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Visualizando detalhes de um FABRICANTE";
}
<div class="panel panel-primary">
    <div class="panel-heading">
        Dados do fabricante a ser removido
    </div>
    <div class="panel-body">
        @Html.Partial("~/Views/Fabricantes/_PartialDetailsContentPanel.cshtml", Model)
    </div>
    <div class="panel-footer panel-info">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <input type="submit" value="Remover FABRICANTE" class="btn btn-danger" />
            @Html.ActionLink("Retornar para a listagem", "Index", null,
            new { @class = "btn btn-info" })
        }
    </div>
</div>
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">
                    Confirmação de exclusão de Fabricante
                </h4>
            </div>
            <div class="modal-body">
                <p>
                    Você está prestes a remover o produto @Model.Nome.ToUpper() do cadastro.
                </p>
                <p>
                    <strong>
                        Você está certo que deseja prosseguir?
                    </strong>
                </p>
                @using (Html.BeginForm("Delete", "Fabricantes", FormMethod.Post,
                new { @id = "delete-form", role = "form" }))
                {
                    @Html.HiddenFor(m => m.FabricanteId)
                    @Html.AntiForgeryToken()
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" onclick="$('#delete-form').submit();">
                    Sim, exclua este produto.
                </button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">
                    Não, não exclua este produto.
                </button>
            </div>
        </div>
    </div>
</div>

WebApplication1/WebApplication1/Views/Fabricantes/Details.cshtml
@model Modelo.Cadastros.Fabricante
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Visualizando detalhes de um FABRICANTE";
}
<div class="panel panel-primary">
    <div class="panel-heading">
        Visualizando detalhes de um FABRICANTE
    </div>
    <div class="panel-body">
        @Html.Partial("~/Views/Fabricantes/_PartialDetailsContentPanel.cshtml", Model)
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("Alterar", "Edit", new { id = Model.FabricanteId },
        new { @class = "btn btn-info" })
        @Html.ActionLink("Retornar para a listagem", "Index", null,
        new { @class = "btn btn-info" })
    </div>
</div>
@section ScriptPage {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

WebApplication1/WebApplication1/Views/Fabricantes/Index.cshtml
@model IEnumerable <Modelo.Cadastros.Fabricante>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Listagem de FABRICANTES";
}
@if (@TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}
<div class="panel panel-primary">
    <div class="panel-heading">
        Relação de FABRICANTES registrados
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FabricanteId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FabricanteId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.ActionLink("Alterar", "Edit", new { id = item.FabricanteId }) |
                            @Html.ActionLink("Detalhes", "Details", new { id = item.FabricanteId }) |
                            @Html.ActionLink("Eliminar", "Delete", new { id = item.FabricanteId })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("Registrar um novo FABRICANTE", "Create", null, new { @class = "btn btn-success" })
    </div>
</div>

@section styles{
    <link href="@Url.Content("~/content/DataTables-1.10.2/css/dataTables.bootstrap.css")" rel="stylesheet" />
}
@section ScriptPage{
    <script src="@Url.Content("~/scripts/DataTables-1.10.2/jquery.dataTables.js")"></script>
    <script src="@Url.Content("~/scripts/DataTables-1.10.2/dataTables.bootstrap.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.table').dataTable({
                "order": [[1, "asc"]]
            });
        });
        $(document).ready(function () {
            $('li').removeClass("active");
            $('#liFabricantes').addClass("active");
        });
    </script>
}

WebApplication1/WebApplication1/Views/Fabricantes/_PartialDetailsContentPanel.cshtml
@model Modelo.Cadastros.Fabricante

<div class="panel-body">
    <div class="form-group">
        @Html.LabelFor(model => model.Nome)
        <br />
        <div class="input-group">
            <span class="input-group-addon">
                <i class="glyphicon glyphicon-user"></i>
            </span>
            @Html.EditorFor(model => model.Nome, new
            {
                htmlAttributes =
            new { @class = "form-control", disabled = "disabled" }
            })
        </div>
    </div>
</div>